version: '3.9'

networks:
  net:
    driver: bridge

services:

  api:
    container_name: rottem-potatoes-api
    build:
      context: .
    depends_on:
      - mongo
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongo
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
    ports:
      - 5000:5000
    networks:
      - net

  mongo:
    container_name: rottem-potatoes-mongo
    image: mongo:6.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ~/.rottem-potatoes/data/db:/data/db
    networks:
      - net

  mongo-express:
    container_name: rottem-potatoes-mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - net
